Vagrant.configure("2") do |config|

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :google do |google, override|
    config.vm.box = "google/gce"

    google.google_project_id = "FIXME: project id"
    google.service_account = "FIXME: email of service account"
    google.google_json_key_location = "FIXME: path to JSON key"

    google.image= "ubuntu-minimal-2404-noble-amd64-v20250923a"
    google.machine_type = "e2-micro"
    google.zone = "us-central1-a"

    override.ssh.username = "FIXME: your username"
    override.ssh.private_key_path = "FIXME: path to your id_ed25519"
  end

end
