Vagrant.configure("2") do |config|

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :google do |google, override|
    config.vm.box = "google/gce"

    google.google_project_id = "FIXME"
    google.service_account = "FIXME"
    google.google_json_key_location = "FIXME"
    google.scopes = ["bigquery", "devstorage.full_control"]

    google.image= "ubuntu-minimal-2404-noble-amd64-v20250923a"
    google.machine_type = "e2-micro"
    google.zone = "us-central1-a"

    override.ssh.username = "FIXME"
    override.ssh.private_key_path = "FIXME"

    config.ssh.extra_args = ["-L", "8000:localhost:8000"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl vim micro virtualenv
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    virtualenv venv
    source ./venv/bin/activate
    echo "source ./venv/bin/activate" >> .bashrc
    pip install sqlmesh[duckdb,bigquery]
    curl https://install.duckdb.org | sh
    echo 'export PATH=~/.duckdb/cli/latest/:$PATH' >> .bashrc

    # mkdir, sqlmesh init
  SHELL

  config.vm.provision "shell", run: "always", privileged: false, inline: <<-SHELL
    # sqlmesh commands here
  SHELL
end

